# Generated by Django 4.2.3 on 2023-07-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='typ',
            field=models.CharField(default='trees', max_length=200),
        ),
    ]
